apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-neg-demo-ingress
  namespace: {{ .Release.Namespace }}
spec:
  defaultBackend:
    service:
      name: {{ .Release.Name }}-neg-demo-svc # Name of the Service targeted by the Ingress
      port:
        number: {{ .Values.service.port }} # Should match the port used by the Service