apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-neg-demo-svc # Name of Service
  namespace: {{ .Release.Namespace }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # Creates a NEG after an Ingress is created
spec: # Service's specification
  type: ClusterIP
  selector:
  {{- range $key, $value := .Values.deployment.labels }}
    {{ $key }}: {{ $value}}
  {{- end }} 
  ports:
  - name: http
    port: {{ .Values.service.port }} # Service's port
    protocol: TCP
    targetPort: {{ .Values.deployment.containerPort }}